REM   Script: PKG_ALUNO
REM   Atividade da matéria Gerenciamento de Banco de Dados.

CREATE OR REPLACE PACKAGE PKG_ALUNO IS 
  PROCEDURE EXCLUIR_ALUNO (P_ID_ALUNO IN NUMBER); 
END PKG_ALUNO; 
/

CREATE OR REPLACE PACKAGE BODY PKG_ALUNO IS 
  PROCEDURE EXCLUIR_ALUNO (P_ID_ALUNO IN NUMBER) IS 
  BEGIN 
    DELETE FROM MATRICULAS WHERE ID_ALUNO = P_ID_ALUNO; 
    DELETE FROM ALUNOS WHERE ID = P_ID_ALUNO; 
  END EXCLUIR_ALUNO; 
END PKG_ALUNO; 
/

CREATE OR REPLACE PACKAGE PKG_ALUNO IS 
  PROCEDURE EXCLUIR_ALUNO (P_ID_ALUNO IN NUMBER); 
END PKG_ALUNO; 
/

CREATE OR REPLACE PACKAGE BODY PKG_ALUNO IS 
  PROCEDURE EXCLUIR_ALUNO (P_ID_ALUNO IN NUMBER) IS 
  BEGIN 
    DELETE FROM MATRICULAS WHERE ID_ALUNO = P_ID_ALUNO; 
    DELETE FROM ALUNOS WHERE ID = P_ID_ALUNO; 
  END EXCLUIR_ALUNO; 
END PKG_ALUNO; 
/

DECLARE 
  CURSOR C_ALUNOS_MAIORES_18 IS 
    SELECT NOME, DATA_NASCIMENTO 
    FROM ALUNOS 
    WHERE FLOOR(MONTHS_BETWEEN(SYSDATE, DATA_NASCIMENTO) / 12) > 18; 
BEGIN 
  FOR R_ALUNOS IN C_ALUNOS_MAIORES_18 LOOP 
    DBMS_OUTPUT.PUT_LINE('Nome: ' || R_ALUNOS.NOME || ', Data de Nascimento: ' || R_ALUNOS.DATA_NASCIMENTO); 
  END LOOP; 
END; 
/

DECLARE 
  CURSOR C_ALUNOS_POR_CURSO (P_ID_CURSO IN NUMBER) IS 
    SELECT NOME 
    FROM ALUNOS A 
    JOIN MATRICULAS M ON A.ID = M.ID_ALUNO 
    WHERE M.ID_CURSO = P_ID_CURSO; 
BEGIN 
  FOR R_ALUNOS IN C_ALUNOS_POR_CURSO(1) LOOP -- Substitua '1' pelo ID do curso desejado 
    DBMS_OUTPUT.PUT_LINE('Nome: ' || R_ALUNOS.NOME); 
  END LOOP; 
END; 
/

